### PR TITLE
Add Plots as a dependency

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
No, make `plot_orbits` a recipe instead.

**Comment by YingboMa** [comment]
How do I do that?

**Comment by ChrisRackauckas** [comment]
https://juliaplots.github.io/recipes/

**Comment by ChrisRackauckas** [comment]
It should only require RecipesBase.jl

**Comment by ChrisRackauckas** [comment]
See the recipes in DiffEqBase.jl for some examples (of type recipes)

**Pull request closed without merging**
