### PR TITLE
support time-dependant Hamiltionians

### PR DESCRIPTION
**Pull request by KlausC**
The old API restricts the Hamiltonian function to signature `H(p, q, param)`, while the mechanism can handle time dependant equations of motion well.

This PR allows for functions with signature `H(p, q, param, t)`.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Should get a breaking tag.

Do any solvers support this well?

**Comment by KlausC** [comment]
> Should get a breaking tag.

I agree, but a weak one. Existing code will break only, if a method with the same name and one additional argument exists.
If there are only methods with the same name and 3 arguments, no change is required.

> Do any solvers support this well?

I would re-formulate the question: are there solvers, which do not perform well, if the RHS is time dependant? In principle I expect all solvers to handle the time dependant case. I don't oversee the restrictions, individual algorithms have, though. Especially the symplectic ones. It is even possible, that some are special cased for partitioned problems where `∂H/∂p(p,q,t)` does not depend on`q` and `t` and `∂H/∂q(p,q,t)` not on `p` and `t`.
 
As I see this API (apart of its physical meaning) a convenient way to specify `dp` and `dq` by a single scalar function `H`, I thought it natural to allow the time dependency of `H` as we do already for `dp` and `dq`.

**Comment by ChrisRackauckas** [comment]
>I would re-formulate the question: are there solvers, which do not perform well, if the RHS is time dependant? In principle I expect all solvers to handle the time dependant case. I don't oversee the restrictions, individual algorithms have, though. Especially the symplectic ones. It is even possible, that some are special cased for partitioned problems where ∂H/∂p(p,q,t) does not depend onq and t and ∂H/∂q(p,q,t) not on p and t.

If the Hamiltonian is time-dependent it won't be symplectic, so the symplectic solvers lose a lot of properties in this case.

I don't think that's a reason to not support it though.

**Comment by ChrisRackauckas** [comment]
Can you add a commit that adds a deprecation warning for using the no-t version? I think we should just enforce the `H(p, q, param, t)` all of the time going forward.

**Pull request merged**
